var subtopics = ["Administrative",
"Compensation",
"Recruiting",
"Product &amp; Design",
"Pitching",
"Business Model",
"Decks",
"Education",
"Entrepreneurs",
"Accounting",
"Capital",
"Debt",
"Equity",
"Revenue Model",
"Competition",
"Customer Development",
"Starting Up",
"Lean",
"Growth",
"Angels",
"Exits",
"Fundraising",
"Investment",
"Valuation",
"Mergers &amp; Acquisitions",
"Negotiation",
"Terms",
"Advisors",
"Board of Directors",
"Introductions",
"Founders",
"Management",
"Marketing",
"Sales",
"Legal/Lawyers",
"Intellectual Property"
];

$(document).ready(function() {
	var template = $("#subtopics-template").html();
	%("#card").html($("#card").html());
});